export function generateXML(project) {
  if (!project) return '';
  const s = project.steps || {};
  const app      = s['app-props']    || {};
  const time     = s['time-profile'] || {};
  const scen     = s['scenario']     || {};
  const curr     = s['currency']     || {};
  const entity   = s['entity']       || {};
  const accounts = s['accounts']     || {};
  const cubes    = s['cube-props']   || {};

  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- OneStream Platform v9 Application Configuration -->\n`;
  xml += `<!-- Generated by OS Accelerator -->\n\n`;
  xml += `<OneStreamApplication>\n`;

  xml += `  <ApplicationProperties>\n`;
  xml += `    <Name>${app.name || 'Unnamed App'}</Name>\n`;
  xml += `    <ApplicationID>${app.appId || 'APP001'}</ApplicationID>\n`;
  xml += `    <Description>${app.description || ''}</Description>\n`;
  xml += `    <DefaultCurrency>${app.currency || 'USD'}</DefaultCurrency>\n`;
  xml += `    <ConsolidationMethod>${app.consol || 'Ownership'}</ConsolidationMethod>\n`;
  xml += `    <PlatformVersion>${app.version || '9.x'}</PlatformVersion>\n`;
  xml += `  </ApplicationProperties>\n\n`;

  xml += `  <TimeProfile>\n`;
  xml += `    <StartYear>${time.startYear || '2020'}</StartYear>\n`;
  xml += `    <EndYear>${time.endYear || '2030'}</EndYear>\n`;
  xml += `    <PeriodFrequency>${time.frequency || 'Monthly'}</PeriodFrequency>\n`;
  xml += `    <FiscalYearEnd>${time.fyEnd || 'December'}</FiscalYearEnd>\n`;
  xml += `    <NumberOfPeriods>${time.periods || '12'}</NumberOfPeriods>\n`;
  xml += `    <PriorPeriods>${time.priorPeriods || '3'}</PriorPeriods>\n`;
  xml += `  </TimeProfile>\n\n`;

  if ((scen.scenarios || []).length) {
    xml += `  <Scenarios>\n`;
    scen.scenarios.forEach((sc) => {
      xml += `    <Scenario><Name>${sc.name}</Name><Type>${sc.type}</Type><LockType>${sc.lock}</LockType></Scenario>\n`;
    });
    xml += `  </Scenarios>\n\n`;
  }

  if ((curr.currencies || []).length) {
    xml += `  <Currencies>\n`;
    curr.currencies.forEach((c) => {
      xml += `    <Currency><ISOCode>${c.code}</ISOCode><Name>${c.name}</Name><IsReporting>${c.default === 'Yes' ? 'true' : 'false'}</IsReporting></Currency>\n`;
    });
    xml += `  </Currencies>\n\n`;
  }

  if ((entity.entities || []).length) {
    xml += `  <EntityHierarchy><TopEntity>${entity.topEntity || 'Total'}</TopEntity>\n`;
    entity.entities.forEach((e) => {
      xml += `    <Entity><Name>${e.name}</Name><Parent>${e.parent}</Parent><Currency>${e.currency || 'USD'}</Currency><Type>${e.type}</Type><ConsolMethod>${e.consol}</ConsolMethod></Entity>\n`;
    });
    xml += `  </EntityHierarchy>\n\n`;
  }

  if ((accounts.accounts || []).length) {
    xml += `  <ChartOfAccounts>\n`;
    accounts.accounts.forEach((a) => {
      xml += `    <Account><Code>${a.code}</Code><Name>${a.name}</Name><Type>${a.type}</Type><FlowType>${a.flow}</FlowType><ICPEnabled>${a.icp === 'Yes' ? 'true' : 'false'}</ICPEnabled></Account>\n`;
    });
    xml += `  </ChartOfAccounts>\n\n`;
  }

  if ((cubes.cubes || []).length) {
    xml += `  <Cubes>\n`;
    cubes.cubes.forEach((c) => {
      xml += `    <Cube><Name>${c.name}</Name><Type>${c.type}</Type></Cube>\n`;
    });
    xml += `  </Cubes>\n\n`;
  }

  xml += `</OneStreamApplication>`;
  return xml;
}
